x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"
    compress: "true"
x-healthcheck: &default-healthcheck
  interval: 1s
  retries: 10
  timeout: 3s

services:
  laravel:
    image: yinyang/frankenphp:php8.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/development/php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./docker/development/supervisord.frankenphp.conf:/etc/supervisor/conf.d/supervisord.frankenphp.conf
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - yinyang_network
    logging:
      <<: *default-logging
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: yinyang
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
    ports:
      - "5432:5432"
    networks:
      - yinyang_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yinyang"]
      <<: *default-healthcheck
    logging:
      <<: *default-logging

  redis:
    image: redis:7.4.0-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - yinyang_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      <<: *default-healthcheck
    logging:
      <<: *default-logging

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: true
      RUSTFS_EXTERNAL_ADDRESS: :9000
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_ACCESS_KEY: rustfs
      RUSTFS_SECRET_KEY: rustfs123
      RUSTFS_LOG_LEVEL: info
    volumes:
      - rustfs_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - yinyang_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      <<: *default-healthcheck
    logging:
      <<: *default-logging

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - yinyang_network
    logging:
      <<: *default-logging

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rustfs_data:
    driver: local

networks:
  yinyang_network:
    driver: bridge
